spring:
  application:
    name: lyx_houtai_web
  profiles:
    active: @package.environment@
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true
server:
  port: 9303
  tomcat: 
      uri-encoding: UTF-8
  http:
      encoding: 
          force: true
          charset: UTF-8
          enabled: true
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:/com/lyx/houtai/mapping/*.xml
  
logging:
  config: classpath:logback.xml
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check